#!/bin/sh
#get fa for *.id.org generated by lineage2idgroup3.batch.pl

in=$1
name=${in/.id.org/}
dirpath='/home/lm/tools/blast2hgt'
query=human51.fa

if [[ `wc -l $name.id.org |cut -f1 -d ' '` -lt 11 ]];then echo "$name.id.org < 11 seqs"; exit;fi # a raw way to skip seqs <11
if [[ ! -f $name.id.org ]];then exit;fi #check if $name.id.org exists
perl $dirpath/phy/num_sp_s.pl $name.id.org 99 >$name.id
awk '{print $2}' $name.id |
blastdbcmd -db ~/ncbi/nr/nr -entry_batch - -target_only >$name.fa.org
perl $dirpath/phy/group2fa2.pl $name.fa.org $name.id >$name.fa
echo $name |perl $dirpath/phy/fasextract.pl $query - >>$name.fa
